apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
      - name: postgresql-data
        emptyDir: {}
      containers:
        - name: postgres
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                  name: postgresql
                  key: database-name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                  name: postgresql
                  key: database-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: postgresql
                  key: database-password
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
          image: postgres
