apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: test-container
    image: gcr.io/google_containers/busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: port
      - name: ENVIRONMENTS
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: environments
  restartPolicy: Never
