apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: xxx
      server: https://kubernetes.docker.internal:6443
    name: my-cluster
  - cluster:
      certificate-authority-data: xxx
      server: https://kubernetes.docker.internal:6443
    name: docker-desktop
contexts:
  - context:
      cluster: my-cluster
      user: myuser
    name: my-cluster
  - context:
      cluster: docker-desktop
      user: docker-desktop
    name: docker-desktop
current-context: my-cluster
kind: Config
preferences: {}
users:
  - name: myuser
    user:
      token: www
  - name: docker-desktop
    user:
      client-certificate-data: xxx
      client-key-data: yyy
