apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: xxx
      server: https://kubernetes.docker.internal:6443
    name: my-cluster
contexts:
  - context:
      cluster: my-cluster
      user: myuser
    name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
  - name: myuser
    user:
      token:
