apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: dev

spec:
  ingressClassName: nginx
  rules:
    - host: test.apps.com
      http:
        paths:
          - path: /
            backend:
              serviceName: my-service
              servicePort: 80
