apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitepress-app
  labels:
    app: vitepress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vitepress
  template:
    metadata:
      labels:
        app: vitepress
    spec:
      containers:
      - name: vitepress
        image: vitepress:latest
        ports:
        - containerPort: 80