apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitepress-app
  labels:
    app: vitepress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vitepress
  template:
    metadata:
      labels:
        app: vitepress
    spec:
      containers:
      - name: vitepress
        image: node:16
        command: ["sh", "-c", "npm install && npm run docs:dev"]
        workingDir: /usr/src/app
        volumeMounts:
        - name: vitepress-volume
          mountPath: /usr/src/app
        ports:
        - containerPort: 8080
      volumes:
      - name: vitepress-volume
        hostPath:
          path: C:/Users/daniele.totisco/source/repos/meral.dev/meral-dev