apiVersion: v1
kind: Service
metadata:
  name: vitepress-service
spec:
  type: NodePort
  selector:
    app: vitepress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007 # Puoi specificare o lasciare che Kubernetes scelga una porta (30000-32767)