apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.sh: |
    #!/bin/bash
    until /usr/bin/mongosh --eval 'printjson(db.serverStatus())'; do
      echo "Sto controllando lo stato del database….."
      sleep 2
    done
    echo "OK."
    HOST=mongo-0.mongo:27017
    until /usr/bin/mongosh --host=${HOST} --eval 'printjson(db.serverStatus())'; do
      echo "Mi sto collegando all’istanza Mongo..."
      sleep 2
    done
    echo "Connesso."
    if [[ "${HOSTNAME}" != 'mongo-0' ]]; then
      until /usr/bin/mongosh --host=${HOST} --eval="printjson(rs.status())" | grep -v "no replset config has been received"; do
      echo "In attesa di configurazione"
      sleep 2
    done
    echo "Sto aggiungendo le repliche."
    /usr/bin/mongosh --host=${HOST} --eval="printjson(rs.add('${HOSTNAME}.mongo'))"
    fi
    if [[ "${HOSTNAME}" == 'mongo-0' ]]; then
      echo "Configurazione del nodo primario"
      /usr/bin/mongosh --eval="printjson(rs.initiate(\
      {'_id': 'rs0', 'members': [{'_id': 0, \
      'host': 'mongo-0.mongo:27017'}]}))"
    fi
    
    echo "Configurazione completata."
    while true; do
      sleep 3600
    done
