apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: wiki
  name: wiki
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
      name: wiki
  type: LoadBalancer
  externalTrafficPolicy: Cluster
