apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: container1
          image: busybox
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "800m"
        - name: container2
          image: busybox
          resources:
            requests:
              memory: "1Gi"
              cpu: "400m"
            limits:
              memory: "2Gi"
              cpu: "600m"

